# Generated by Django 4.1.7 on 2023-02-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookuploadmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('bookimage', models.ImageField(upload_to='static/bookapp')),
            ],
        ),
    ]
