# Generated by Django 4.1.7 on 2023-03-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_profileload'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookuploadmodel',
            name='shopid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
