# Generated by Django 4.1.7 on 2023-03-02 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_bookuploadmodel_shopid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bookuploadmodel',
        ),
        migrations.RemoveField(
            model_name='profileload',
            name='user',
        ),
        migrations.DeleteModel(
            name='shopregistermodel',
        ),
        migrations.DeleteModel(
            name='profileload',
        ),
    ]
