# Generated by Django 4.1.7 on 2023-03-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookapp', '0005_delete_bookuploadmodel_remove_profileload_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=30)),
                ('bookpdf', models.FileField(upload_to='')),
                ('bookimage', models.ImageField(upload_to='bookapp/static')),
                ('author', models.CharField(max_length=30)),
                ('bookdate', models.DateField()),
            ],
        ),
    ]
