# Generated by Django 4.1.7 on 2023-03-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='bookimage',
            field=models.FileField(upload_to='bookapp/static'),
        ),
    ]
