# Generated by Django 4.1.7 on 2023-03-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_alter_bookmodel_bookimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='bookpdf',
            field=models.FileField(upload_to='bookapp/static'),
        ),
    ]
